### ISSUE TITLE
Add sample interpolation results

### ISSUE THREAD

**Issue by saikatdutta** [lyh-18/EQVI#1]
Can you add sample interpolation results so that we can check the model is properly working on our system(by comparing PSNR/SSIM)? This should be helpful because different Pytorch and GCC versions might produce different results.

**Comment by lyh-18** [comment]
> Can you add sample interpolation results so that we can check the model is properly working on our system(by comparing PSNR/SSIM)? This should be helpful because different Pytorch and GCC versions might produce different results.

Hi, thanks for your suggestions. We have uploaded two sample interpolated results at Google Drive for you information. Please check the updated readme file~
