### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'int' and 'dict'

### ISSUE THREAD

**Issue by John-Yao** [lyh-18/EQVI#3]
Hi,

I try to use the model in our repo. And I got some error as below:
`    
return 20*output_dict_eval
TypeError: unsupported operand type(s) for *: 'int' and 'dict'
`
I am curious about why 20 is multiply with output_dict_eval, which is not occurres in official repo of Scopflow .

**Comment by lyh-18** [comment]
In our tesing scripts, the codes defaultly go through the other branch `20*output_dict['flow'][-1][0]`. We have updated the scripts to avoid differences here.
The reason why we have a factor of 20 here is that we adopt the default settings of scopeflow which normalizes the flow output by dividing 20 `def __init__(self, args, div_flow=0.05):` (Line16 in IRR_PWC_V2.py). Thus we manually multiply 20.

**Comment by John-Yao** [comment]
Thanks for your reply and release the training codes! Good Job!

I am also confuse about the REDS_VTSR5 mentioned in the paper. Does it include 30 validation clips? And the released 

checkpoints are training using 30 validation clips?

**Comment by lyh-18** [comment]
REDS_VTSR5 is a subset of REDS_VTSR validation set, which is composed of  002, 005, 010, 017 and 025. It is used to conduct quick validation during training.
The released pretrained models are only trained on REDS_VTSR training set, which includes 240 clips. The REDS_VTSR validation set is another 30 clips and REDS_VTSR5 is a subset of EDS_VTSR validation set .

**Comment by John-Yao** [comment]
Got it!
