### ISSUE TITLE
Training files

### ISSUE THREAD

**Issue by rsjjdesj** [lyh-18/EQVI#5]
Hello: could you please provide the files to reproduce the training steps on gpu and cpu (for example for a small dataset).

**Comment by lyh-18** [comment]
We have just released the trainign codes.
Since the training procedure takes a lot of  storage memories and it costs much time. We recommend to train the model on GPUs.

**Comment by rsjjdesj** [comment]
Thanks for sharing the files. I wanted to know if the pytorch code supports training on cpu for a very small dataset. This is to understand the flow in windows using pycharm etc.

For bigger training, yes I understand GPU is recommended. Also, I see that you have mentioned that you used 2080 for training. Will it work with previous generation GPU's.

**Comment by lyh-18** [comment]
I guess it is okay to run the codes on Windows platform and on CPU. However, I have not tried it. Maybe there should be some adjustments for the codes.

I think other GPU can work well, only if it supports CUDA>=9 and Pytorch>=1.2.
