### ISSUE TITLE
subtitle in the movie

### ISSUE THREAD

**Issue by leiwen83** [lyh-18/EQVI#6]
Hi,

Lots of interpolation method suffers from the subtitle issue, which in video like movie accompany with subtitle, while has great motion between two frame. It would cause subtitle area become blurry or complete damaged.

I wonder know whether your method could handle well in this case?

Thx,
Lei

**Comment by lyh-18** [comment]
We have not tried our method on videos with subtitle in them. You can try to use our pretrained model to test such cases. However,  it is common that most frame interpolation methods will suffer from severe artifacts, even produce failure cases, when large motion occurs. It is challenging but important for researchers to explore the large motion solution.
